### ISSUE TITLE
Usage of idomatic scala operators for scan, reduce, fold etc.

### ISSUE THREAD

**Issue by jpork** [reactor/reactor-scala-extensions#52]
Currently SFlux and SMono use the Java idiomatic way to express operators like scan, fold, reduce etc.
See this example for scan:

```
SFlux.just("item1", "item2")
  .scan**[String]**("prefix", (acc, value) => acc + value)
```
The Scala idiomatic equivalent would use a second parameter list:
```
Seq("item1", "item2")
  .scan("prefix")((acc, value) => acc + value)
```
Doing it this way one would gain closure notation like so:
```
Seq("item1", "item2")
  .scan("prefix"){(acc, value) =>
    println(s"$acc, $value")  
    acc + value}
```
This would especially be quite helpful when using multi-line closures.

For the scan operator (true for others too) I need to declare the generic type `scan[String]` in order to compile. This should also not be necessary.

The operator semantic also slightly diverges. Scala collections don't have `reduce` with initial value. Its called `fold` there.

All SFlux operators should be converted semantically and syntactically equal to them known from Scala collections. 

For example [RxScala](http://reactivex.io/rxscala/scaladoc/index.html#rx.lang.scala.Observable) did it that way.

**Comment by sinwe** [comment]
Thanks @jpork. I can add this to 0.6.x.
However the `SFlux` operators are a lot and I'd need help to identify those that requires alignment to Scala collections.
Initial idea of this library was to have scala fluency of using project reactor. It was more to align to reactor library so that developers familiar with underlying java library doesn't have difficulties to find the corresponding operator in Scala.
While we can align it more to Scala collections, we need to make sure that we do not to remove access to the operators that underlying reactor library provides.

**Comment by jpork** [comment]
I guess when it comes to converting Supplier[T] to scala the call by-name parameter way is a smoother choice than the Function0[T] variant.

`def scan[A](init: => A)  // by-name parameter`
